//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanUp.Migrations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _201709150904080_new_m {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _201709150904080_new_m() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlanUp.Migrations.201709150904080_new m", typeof(_201709150904080_new_m).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.
        /// </summary>
        internal static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAEAN1c227jNhB9L9B/EPTUFqmVS3exDewWqZN0g24uWCdF3xa0RDvCSpQqUWmCol/Wh35Sf6GkRN14kShZtpViX2KJPDMcHpLD0cz++/c/0x+ffc94glHsBmhmHk0OTQMiO3BctJ6ZCV59+8788Ycvv5heOP6z8Wve7oS2Iz1RPDMfMQ5PLSu2H6EP4onv2lEQBys8sQPfAk5gHR8efm8dHVmQQJgEyzCmHxOEXR+mP8jPeYBsGOIEeNeBA72YPSdvFimqcQN8GIfAhjPzzgPoIZxkDU3jzHMBUWIBvZVpAIQCDDBR8fQhhgscBWi9CMkD4N2/hJC0WwEvhkz107K57igOj+korLJjDmUnMQ78joBHJ8wsFt+9l3HNwmzEcBfEwPiFjjo13sx8H/jw4gkibBq8tNO5F9GWnHEnRZcDI3txUDCAEIX+OzDmiYeTCM4QTHAEPNIyWXqu/Qt8uQ8+QzRDiedVFSOqkXe1B+TRXRSEMMIvH+GK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
