//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanUp.Migrations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _201709141258067_add_homeEvents_table {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _201709141258067_add_homeEvents_table() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlanUp.Migrations.201709141258067_add homeEvents table", typeof(_201709141258067_add_homeEvents_table).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.
        /// </summary>
        internal static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAEAOVdW2/ruBF+L9D/IOipLbJ2Lj0Hp4G9i6yTdIOeXHCcLPp2QEu0IxyJ0kpUNkGxv2wf+pP6F0rqyqtEybKttNiXWBx+MxwOyeFw5ux/fv/37IfXwLdeYJx4IZrbJ5Nj24LICV0PbeZ2itfffbJ/+P6Pf5hducGr9XNJd0bpSE+UzO1njKPz6TRxnmEAkkngOXGYhGs8ccJgCtxwenp8/LfpyckUEgibYFnW7EuKsBfA7Af5uQiRAyOcAv82dKGfFN9JyzJDte5AAJMIOHBuP/gAPUWTnNC2LnwPECGW0F/bFkAoxAATEc+fErjEcYg2y4h8AP7jWwQJ3Rr4CSxEP6/JTUdxfEpHMa07llBOmuAw6Ah4claoZSp276Vcu1IbUdwVUTB+o6POlDe3fwoDePUCEbYtkdv5wo8ppaDcSdXlyMobjioLIIZC/zuyFqmP0xjOEUxxDHxCma58z/kHfHsMv0E0R6nvs4IR0Ugb94F8eojDCMb4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
